const titles = {
  "data": {
    "configuration": {
      "body": {
        "data": {
          "tabs": {
            "GeneralExplanation": {
              "urlEnglishStudies": "https://languages.tau.ac.il/english",
              "year_label": "שנת הלימודים",
              "studyYear": "שנה\"ל",
              "degreeStructure": "מבנה הלימודים",
              "degreeTotalHours": "מכסת שעות לתואר",
              "necessaryLinks": "קישורים חיוניים",
              "universityInstructions": "נוהלי האוניברסיטה",
              "registerBidding": "רישום לבידינג",
              "readMore": "קרא עוד",
              "universityInstructionsUrl": "https://acad-sec.tau.ac.il/info/main",
              "registerBiddingUrl": " https://www.ims.tau.ac.il/Bidd/",
              "englishStudies": "לימודי אנגלית לרמת פטור ",
              "hebrewStudies": "לימודי עברית לרמת פטור",
              "searchCourses": "חיפוש קורסים",
              "celimShluvim": "כלים שלובים",
              "calendar": "לוח שנה\"ל",
              "tuitionMain": "תקנות שכר לימוד",
              "campusMap": "מפת הקמפוס",
              "urlHebrewStudies": "https://hebrewcenterta.wixsite.com/hebrewcenter",
              "urlSearchCourses": "https://www.ims.tau.ac.il/tal/kr/search_p.aspx",
              "urlCelimShluvim": "https://core.tau.ac.il",
              "urlSharRuach": "https://humanities.tau.ac.il/shar_ruach",
              "urlCalendar": "https://www.tau.ac.il/calendar",
              "urlTuitionMain": "https://www.tau.ac.il/tuition-main",
              "urlCampusMap": "https://maintenanceapps.tau.ac.il/documents/map/detailed-tel-aviv-university-map-hebrew.pdf",
              "regulations": "תקנונים",
              "sharRuach": "שאר רוח"
            },
            "programStudy": {
              "drishotmakbilot": "דרישות מקבילות",
              "studyYear": "שנה\"ל",
              "updates": "עדכונים",
              "formerYedions": "ידיעונים קודמים",
              "viewSchedule": "לצפייה במערכת שעות",
              "teachingMethod": "אופן הוראה",
              "totalHours": "סה\"כ שעות",
              "weight": "משקל בציון",
              "passingGrade": "ציון מעבר",
              "requirements": "דרישות",
              "drishotkedem": "דרישות קדם",
              "sumShaot": "סה\"כ",
              "hesberKavuhaTitle": "מבנה תוכנית הלימודים לתלמידים המתחילים לימודיהם בשנה\"ל ",
              "hesberKavuhaContent": "תלמידים שהחלו לימודיהם בתוכנית בשנים קודמות יוכלו לעיין במבנה התוכנית הרלוונטי להם בלשונית \"ידיעונים קודמים\" בעמוד זה. ",
              "medicShavuot": "מספר שבועות",
              "medicMishkal": "משקל",
              "related": "שייך ל:",
              "or": "או",
              "medicSemHours": "מס' ש\"ס",
              "medicTime": "שבועות",
              "yearStudies": "מבנה תוכנית הלימודים - "
            },
            "schedule": {
              "viewSchedule": "לצפייה במערכת שעות",
              "hourRange": "טווח שעות",
              "daysInWeek": "ימים בשבוע",
              "openPopup": "פתח פופ אפ",
              "from": "מהשעה",
              "until": "עד השעה",
              "approve": "אישור",
              "studyYear": "שנה\"ל",
              "semesterBlockTitle": "סמסטר",
              "machatzitBlockTitle": "מחצית",
              "invalidHourInput": "טווח שעות אינו תקין",
              "hourInput": "שדה מילוי שעות",
              "minuteInput": "שדה מילוי דקות",
              "notFinalMessage": "ייתכנו שינויים במערכת השעות. יש להתעדכן באתר באופן שוטף.",
              "onlineCourse": "קורס מקוון ",
              "scheduleForTheYear": "מערכת שעות לשנת הלימודים",
              "filterByCourseId": "מיון לפי מספר קורס",
              "teachingMethod": "אופן הוראה",
              "teacher": "מורה ",
              "frequency": "תדירות",
              "location": "מיקום",
              "scheduleByManot": "מערכת שעות לפי מנות",
              "notYetPublished": "מערכת השעות תפורסם בהמשך",
              "gilmanScheduleMsg": "המידע לגבי מועדי הבחינות והגשת עבודות הרשומים בסילבוסים, מיועד לתלמידים מן המניין בלבד, ולא לתלמידי לומדים בגילמן שאינם זכאים להבחן או להגיש עבודות",
              "medicShavuotSchedule": "שבועות",
              "showMoreZamak": "זמני קורס נוספים >",
              "semShnati": "שנתי",
              "medicSemHours": "מס' ש\"ס",
              "medicTime": "שבועות",
              "yearStudies": "מבנה תוכנית הלימודים - "
            },
            "assignments": {
              "notFinalMessage": "ייתכנו שינויים בלוח הבחינות. יש להתעדכן באתר באופן שוטף.",
              "assignmentsForTheYear": "לוח בחינות ומטלות לשנת הלימודים",
              "assignmentsNotYetPublished": "לוח הבחינות והמטלות יפורסם בהמשך",
              "tmatalalekiha": "תאריך ושעת פרסום מטלה",
              "tmatalahachzara": "תאריך ושעת הגשת מטלה",
              "showMoreKvutza": "זמני קורס נוספים >",
              "yearStudies": "מבנה תוכנית הלימודים - "
            },
            "search": {
              "placeholder": "איזו תכנית מעניינת אותך?",
              "noResults": "אין תוצאות",
              "canSpecify": "תמיד אפשר לדייק",
              "degreeLevel": "רמת תואר ואופן לימוד",
              "textEmptyResults": "לא נמצאו תוצאות המתאימות לחיפוש שלך",
              "textUniversityInformation": "לידיעון המלא של האוניברסיטה",
              "linkUniversityInformation": "https://www.tau.ac.il/search-studies-programs"
            },
            "general": {
              "hourRange": "טווח שעות",
              "daysInWeek": "ימים בשבוע",
              "resetSearchFilters": "ניקוי סינון וחיפוש",
              "actualYear": "",
              "searchBarPlaceholder": "חיפוש",
              "noResults": "אין תוצאות",
              "semesterBlockTitle": "סמסטר",
              "machatzitBlockTitle": "מחצית",
              "filterAndSearch": "סינון וחיפוש",
              "studyYear": "שנה\"ל",
              "from": "מהשעה",
              "until": "עד השעה",
              "approve": "אישור",
              "invalidHourInput": "טווח שעות אינו תקין",
              "degreeGiven": "התואר המוענק:",
              "generalExplanation": "הסבר כללי",
              "programStudy": "תוכנית לימודים",
              "schedule": "מערכת שעות",
              "assignments": "לוח בחינות ומטלות",
              "onlineCourse": "קורס מקוון",
              "safaToolTipSymbol": "EN",
              "": "",
              "group": "קבוצה",
              "semester": "סמסטר",
              "date": "תאריך",
              "cycle": "מחזור",
              "assignmentType": "סוג מטלה",
              "dueDate": "מועד",
              "teachingMethod": "אופן הוראה",
              "CourseId": "מספר קורס",
              "course": "קורס",
              "sunday": "א",
              "monday": "ב",
              "tuesday": "ג",
              "wednesday": "ד",
              "thursday": "ה",
              "friday": "ו",
              "submit": "אישור",
              "shoatShas": "ש\"ס",
              "textEmptyResults": "לא נמצאו תוצאות המתאימות לחיפוש שלך",
              "showReadMore": "קרא עוד",
              "showReadLess": "קרא פחות",
              "day": "יום",
              "closeAccordions": "סגר/י הכל",
              "openAccordions": "פתח/י הכל",
              "filterButton": "סינון",
              "collapse": "הסתר",
              "unPublishedTitle": "תוכנית הלימודים תפורסם בהמשך",
              "courseAvailableInEnglish": "הקורס ניתן באנגלית"
            }
          }
        },
        "method": "GET"
      },
      "__typename": "Response"
    }
  }
}

export default titles;